### ISSUE TITLE
Dynamically Parse Object Arrays

### ISSUE THREAD

**Issue by introsuit** [peterbourgon/ff#135]
We are encountering an issue where we are unable to dynamically parse arrays of objects from a YAML configuration file.

Example YAML Configuration:
```
push:
  fcm:
    - name: "app1"
      project-id: "foo"
      service-account: "bar"

    - name: "app2"
      project-id: "baz"
      service-account: "qux"
```

When attempting to parse the above structure using `ffyaml`, we are unable to convert this configuration into a struct array. For instance, using `fs.Var(&cfg.Push, "push", "")` won't do the trick. The logic traversing the structure skips the array because it assumes there is nothing to parse.

It appears that while `ff` can handle nested structures, it struggles with arrays of objects or maps. The `traverse_map()` function (see [source code](https://github.com/peterbourgon/ff/blob/main/internal/ffdata/traverse_map.go)) recursively traverses the configuration until it finds a primitive type in the nested structure, rather than providing an option to handle parsing the entire structure.

We are seeking thoughts or proposals for future implementation to address this issue. Any suggestions on how to effectively handle the parsing of such nested arrays of objects would be greatly appreciated.
